#ifndef HL7PARSER_SEG_DSC_H
#define HL7PARSER_SEG_DSC_H

/**
* \file seg_dsc.h
*
* Continuation pointer segment (DSC) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the continuation_pointer (DSC.1) field.
*/
HL7_EXPORT HL7_Element *hl7_dsc_continuation_pointer( HL7_Segment *segment );
/**
* Set the continuation_pointer (DSC.1) field.
*/
HL7_EXPORT int hl7_dsc_set_continuation_pointer( HL7_Segment *segment, HL7_Element *element );
/**
* Set the continuation_pointer (DSC.1) field as a string.
*/
HL7_EXPORT int hl7_dsc_set_continuation_pointer_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_DSC_H */
