#ifndef HL7PARSER_SEG_QAK_H
#define HL7PARSER_SEG_QAK_H

/**
* \file seg_qak.h
*
* Query acknowledgment segment (QAK) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the query_tag (QAK.1) field.
*/
HL7_EXPORT HL7_Element *hl7_qak_query_tag( HL7_Segment *segment );
/**
* Set the query_tag (QAK.1) field.
*/
HL7_EXPORT int hl7_qak_set_query_tag( HL7_Segment *segment, HL7_Element *element );
/**
* Set the query_tag (QAK.1) field as a string.
*/
HL7_EXPORT int hl7_qak_set_query_tag_str( HL7_Segment *segment, const char *value );
/**
* Get the query_response_status (QAK.2) field.
*/
HL7_EXPORT HL7_Element *hl7_qak_query_response_status( HL7_Segment *segment );
/**
* Set the query_response_status (QAK.2) field.
*/
HL7_EXPORT int hl7_qak_set_query_response_status( HL7_Segment *segment, HL7_Element *element );
/**
* Set the query_response_status (QAK.2) field as a string.
*/
HL7_EXPORT int hl7_qak_set_query_response_status_str( HL7_Segment *segment, const char *value );
/**
* Get the query_id (QAK.3.1) component.
*/
HL7_EXPORT HL7_Element *hl7_qak_query_id( HL7_Segment *segment );
/**
* Set the query_id (QAK.3.1) component.
*/
HL7_EXPORT int hl7_qak_set_query_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the query_id (QAK.3.1) component as a string.
*/
HL7_EXPORT int hl7_qak_set_query_id_str( HL7_Segment *segment, const char *value );
/**
* Get the query_name (QAK.3.2) component.
*/
HL7_EXPORT HL7_Element *hl7_qak_query_name( HL7_Segment *segment );
/**
* Set the query_name (QAK.3.2) component.
*/
HL7_EXPORT int hl7_qak_set_query_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the query_name (QAK.3.2) component as a string.
*/
HL7_EXPORT int hl7_qak_set_query_name_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_QAK_H */
