#ifndef HL7PARSER_SEG_ZIN_H
#define HL7PARSER_SEG_ZIN_H

/**
* \file seg_zin.h
*
* Additional insurance information segment (ZIN) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the eligibility_indicator (ZIN.1) field.
*/
HL7_EXPORT HL7_Element *hl7_zin_eligibility_indicator( HL7_Segment *segment );
/**
* Set the eligibility_indicator (ZIN.1) field.
*/
HL7_EXPORT int hl7_zin_set_eligibility_indicator( HL7_Segment *segment, HL7_Element *element );
/**
* Set the eligibility_indicator (ZIN.1) field as a string.
*/
HL7_EXPORT int hl7_zin_set_eligibility_indicator_str( HL7_Segment *segment, const char *value );
/**
* Get the patient_vat_status (ZIN.2.1) component.
*/
HL7_EXPORT HL7_Element *hl7_zin_patient_vat_status( HL7_Segment *segment );
/**
* Set the patient_vat_status (ZIN.2.1) component.
*/
HL7_EXPORT int hl7_zin_set_patient_vat_status( HL7_Segment *segment, HL7_Element *element );
/**
* Set the patient_vat_status (ZIN.2.1) component as a string.
*/
HL7_EXPORT int hl7_zin_set_patient_vat_status_str( HL7_Segment *segment, const char *value );
/**
* Get the patient_vat_status_text (ZIN.2.2) component.
*/
HL7_EXPORT HL7_Element *hl7_zin_patient_vat_status_text( HL7_Segment *segment );
/**
* Set the patient_vat_status_text (ZIN.2.2) component.
*/
HL7_EXPORT int hl7_zin_set_patient_vat_status_text( HL7_Segment *segment, HL7_Element *element );
/**
* Set the patient_vat_status_text (ZIN.2.2) component as a string.
*/
HL7_EXPORT int hl7_zin_set_patient_vat_status_text_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_ZIN_H */
