#ifndef HL7PARSER_SEG_RF1_H
#define HL7PARSER_SEG_RF1_H

/**
* \file seg_rf1.h
*
* Referral information segment (RF1) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the referral_status_id (RF1.1.1) component.
*/
HL7_EXPORT HL7_Element *hl7_rf1_referral_status_id( HL7_Segment *segment );
/**
* Set the referral_status_id (RF1.1.1) component.
*/
HL7_EXPORT int hl7_rf1_set_referral_status_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the referral_status_id (RF1.1.1) component as a string.
*/
HL7_EXPORT int hl7_rf1_set_referral_status_id_str( HL7_Segment *segment, const char *value );
/**
* Get the referral_status_description (RF1.1.2) component.
*/
HL7_EXPORT HL7_Element *hl7_rf1_referral_status_description( HL7_Segment *segment );
/**
* Set the referral_status_description (RF1.1.2) component.
*/
HL7_EXPORT int hl7_rf1_set_referral_status_description( HL7_Segment *segment, HL7_Element *element );
/**
* Set the referral_status_description (RF1.1.2) component as a string.
*/
HL7_EXPORT int hl7_rf1_set_referral_status_description_str( HL7_Segment *segment, const char *value );
/**
* Get the referral_type_id (RF1.3.1) component.
*/
HL7_EXPORT HL7_Element *hl7_rf1_referral_type_id( HL7_Segment *segment );
/**
* Set the referral_type_id (RF1.3.1) component.
*/
HL7_EXPORT int hl7_rf1_set_referral_type_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the referral_type_id (RF1.3.1) component as a string.
*/
HL7_EXPORT int hl7_rf1_set_referral_type_id_str( HL7_Segment *segment, const char *value );
/**
* Get the referral_type_description (RF1.3.2) component.
*/
HL7_EXPORT HL7_Element *hl7_rf1_referral_type_description( HL7_Segment *segment );
/**
* Set the referral_type_description (RF1.3.2) component.
*/
HL7_EXPORT int hl7_rf1_set_referral_type_description( HL7_Segment *segment, HL7_Element *element );
/**
* Set the referral_type_description (RF1.3.2) component as a string.
*/
HL7_EXPORT int hl7_rf1_set_referral_type_description_str( HL7_Segment *segment, const char *value );
/**
* Get the originating_referral_id (RF1.6.1) component.
*/
HL7_EXPORT HL7_Element *hl7_rf1_originating_referral_id( HL7_Segment *segment );
/**
* Set the originating_referral_id (RF1.6.1) component.
*/
HL7_EXPORT int hl7_rf1_set_originating_referral_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the originating_referral_id (RF1.6.1) component as a string.
*/
HL7_EXPORT int hl7_rf1_set_originating_referral_id_str( HL7_Segment *segment, const char *value );
/**
* Get the effective_date (RF1.7) field.
*/
HL7_EXPORT time_t hl7_rf1_effective_date( HL7_Segment *segment );
/**
* Set the effective_date (RF1.7) field.
*/
HL7_EXPORT int hl7_rf1_set_effective_date( HL7_Segment *segment, HL7_Element *element );
/**
* Set the effective_date (RF1.7) field as a time_t.
*/
HL7_EXPORT int hl7_rf1_set_effective_date_time( HL7_Segment *segment, const time_t value );
/**
* Get the expiration_date (RF1.8) field.
*/
HL7_EXPORT time_t hl7_rf1_expiration_date( HL7_Segment *segment );
/**
* Set the expiration_date (RF1.8) field.
*/
HL7_EXPORT int hl7_rf1_set_expiration_date( HL7_Segment *segment, HL7_Element *element );
/**
* Set the expiration_date (RF1.8) field as a time_t.
*/
HL7_EXPORT int hl7_rf1_set_expiration_date_time( HL7_Segment *segment, const time_t value );
/**
* Get the process_date (RF1.9) field.
*/
HL7_EXPORT time_t hl7_rf1_process_date( HL7_Segment *segment );
/**
* Set the process_date (RF1.9) field.
*/
HL7_EXPORT int hl7_rf1_set_process_date( HL7_Segment *segment, HL7_Element *element );
/**
* Set the process_date (RF1.9) field as a time_t.
*/
HL7_EXPORT int hl7_rf1_set_process_date_time( HL7_Segment *segment, const time_t value );
/**
* Get the referral_reason_id (RF1.10.1) component.
*/
HL7_EXPORT HL7_Element *hl7_rf1_referral_reason_id( HL7_Segment *segment );
/**
* Set the referral_reason_id (RF1.10.1) component.
*/
HL7_EXPORT int hl7_rf1_set_referral_reason_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the referral_reason_id (RF1.10.1) component as a string.
*/
HL7_EXPORT int hl7_rf1_set_referral_reason_id_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_RF1_H */
