#ifndef HL7PARSER_SEG_NTE_H
#define HL7PARSER_SEG_NTE_H

/**
* \file seg_nte.h
*
* Notes and comments segment (NTE) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the set_id (NTE.1) field.
*/
HL7_EXPORT int hl7_nte_set_id( HL7_Segment *segment );
/**
* Set the set_id (NTE.1) field.
*/
HL7_EXPORT int hl7_nte_set_set_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the set_id (NTE.1) field as an integer.
*/
HL7_EXPORT int hl7_nte_set_set_id_int( HL7_Segment *segment, const int value );
/**
* Get the comment (NTE.3) field.
*/
HL7_EXPORT HL7_Element *hl7_nte_comment( HL7_Segment *segment );
/**
* Set the comment (NTE.3) field.
*/
HL7_EXPORT int hl7_nte_set_comment( HL7_Segment *segment, HL7_Element *element );
/**
* Set the comment (NTE.3) field as a string.
*/
HL7_EXPORT int hl7_nte_set_comment_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_NTE_H */
