#ifndef HL7PARSER_SEG_QPD_Q15_H
#define HL7PARSER_SEG_QPD_Q15_H

/**
* \file seg_qpd_q15.h
*
* Query parameter definition -- procedure totals query segment (QPD_Q15) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the query_id (QPD_Q15.1.1) component.
*/
HL7_EXPORT HL7_Element *hl7_qpd_q15_query_id( HL7_Segment *segment );
/**
* Set the query_id (QPD_Q15.1.1) component.
*/
HL7_EXPORT int hl7_qpd_q15_set_query_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the query_id (QPD_Q15.1.1) component as a string.
*/
HL7_EXPORT int hl7_qpd_q15_set_query_id_str( HL7_Segment *segment, const char *value );
/**
* Get the query_name (QPD_Q15.1.2) component.
*/
HL7_EXPORT HL7_Element *hl7_qpd_q15_query_name( HL7_Segment *segment );
/**
* Set the query_name (QPD_Q15.1.2) component.
*/
HL7_EXPORT int hl7_qpd_q15_set_query_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the query_name (QPD_Q15.1.2) component as a string.
*/
HL7_EXPORT int hl7_qpd_q15_set_query_name_str( HL7_Segment *segment, const char *value );
/**
* Get the query_tag (QPD_Q15.2) field.
*/
HL7_EXPORT HL7_Element *hl7_qpd_q15_query_tag( HL7_Segment *segment );
/**
* Set the query_tag (QPD_Q15.2) field.
*/
HL7_EXPORT int hl7_qpd_q15_set_query_tag( HL7_Segment *segment, HL7_Element *element );
/**
* Set the query_tag (QPD_Q15.2) field as a string.
*/
HL7_EXPORT int hl7_qpd_q15_set_query_tag_str( HL7_Segment *segment, const char *value );
/**
* Get the provider_id (QPD_Q15.3.1) component.
*/
HL7_EXPORT HL7_Element *hl7_qpd_q15_provider_id( HL7_Segment *segment );
/**
* Set the provider_id (QPD_Q15.3.1) component.
*/
HL7_EXPORT int hl7_qpd_q15_set_provider_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the provider_id (QPD_Q15.3.1) component as a string.
*/
HL7_EXPORT int hl7_qpd_q15_set_provider_id_str( HL7_Segment *segment, const char *value );
/**
* Get the provider_id_type (QPD_Q15.3.2) component.
*/
HL7_EXPORT HL7_Element *hl7_qpd_q15_provider_id_type( HL7_Segment *segment );
/**
* Set the provider_id_type (QPD_Q15.3.2) component.
*/
HL7_EXPORT int hl7_qpd_q15_set_provider_id_type( HL7_Segment *segment, HL7_Element *element );
/**
* Set the provider_id_type (QPD_Q15.3.2) component as a string.
*/
HL7_EXPORT int hl7_qpd_q15_set_provider_id_type_str( HL7_Segment *segment, const char *value );
/**
* Get the start_date (QPD_Q15.4) field.
*/
HL7_EXPORT time_t hl7_qpd_q15_start_date( HL7_Segment *segment );
/**
* Set the start_date (QPD_Q15.4) field.
*/
HL7_EXPORT int hl7_qpd_q15_set_start_date( HL7_Segment *segment, HL7_Element *element );
/**
* Set the start_date (QPD_Q15.4) field as a time_t.
*/
HL7_EXPORT int hl7_qpd_q15_set_start_date_time( HL7_Segment *segment, const time_t value );
/**
* Get the end_date (QPD_Q15.5) field.
*/
HL7_EXPORT time_t hl7_qpd_q15_end_date( HL7_Segment *segment );
/**
* Set the end_date (QPD_Q15.5) field.
*/
HL7_EXPORT int hl7_qpd_q15_set_end_date( HL7_Segment *segment, HL7_Element *element );
/**
* Set the end_date (QPD_Q15.5) field as a time_t.
*/
HL7_EXPORT int hl7_qpd_q15_set_end_date_time( HL7_Segment *segment, const time_t value );
/**
* Get the procedure_id (QPD_Q15.6.1) component.
*/
HL7_EXPORT HL7_Element *hl7_qpd_q15_procedure_id( HL7_Segment *segment );
/**
* Set the procedure_id (QPD_Q15.6.1) component.
*/
HL7_EXPORT int hl7_qpd_q15_set_procedure_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the procedure_id (QPD_Q15.6.1) component as a string.
*/
HL7_EXPORT int hl7_qpd_q15_set_procedure_id_str( HL7_Segment *segment, const char *value );
/**
* Get the procedure_coding_system (QPD_Q15.6.2) component.
*/
HL7_EXPORT HL7_Element *hl7_qpd_q15_procedure_coding_system( HL7_Segment *segment );
/**
* Set the procedure_coding_system (QPD_Q15.6.2) component.
*/
HL7_EXPORT int hl7_qpd_q15_set_procedure_coding_system( HL7_Segment *segment, HL7_Element *element );
/**
* Set the procedure_coding_system (QPD_Q15.6.2) component as a string.
*/
HL7_EXPORT int hl7_qpd_q15_set_procedure_coding_system_str( HL7_Segment *segment, const char *value );
/**
* Get the authorizer_id (QPD_Q15.7.1) component.
*/
HL7_EXPORT HL7_Element *hl7_qpd_q15_authorizer_id( HL7_Segment *segment );
/**
* Set the authorizer_id (QPD_Q15.7.1) component.
*/
HL7_EXPORT int hl7_qpd_q15_set_authorizer_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the authorizer_id (QPD_Q15.7.1) component as a string.
*/
HL7_EXPORT int hl7_qpd_q15_set_authorizer_id_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_QPD_Q15_H */
