#ifndef HL7PARSER_SEG_IN1_H
#define HL7PARSER_SEG_IN1_H

/**
* \file seg_in1.h
*
* Insurance segment (IN1) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the set_id (IN1.1) field.
*/
HL7_EXPORT int hl7_in1_set_id( HL7_Segment *segment );
/**
* Set the set_id (IN1.1) field.
*/
HL7_EXPORT int hl7_in1_set_set_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the set_id (IN1.1) field as an integer.
*/
HL7_EXPORT int hl7_in1_set_set_id_int( HL7_Segment *segment, const int value );
/**
* Get the plan_id (IN1.2.1) component.
*/
HL7_EXPORT HL7_Element *hl7_in1_plan_id( HL7_Segment *segment );
/**
* Set the plan_id (IN1.2.1) component.
*/
HL7_EXPORT int hl7_in1_set_plan_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the plan_id (IN1.2.1) component as a string.
*/
HL7_EXPORT int hl7_in1_set_plan_id_str( HL7_Segment *segment, const char *value );
/**
* Get the plan_name (IN1.2.2) component.
*/
HL7_EXPORT HL7_Element *hl7_in1_plan_name( HL7_Segment *segment );
/**
* Set the plan_name (IN1.2.2) component.
*/
HL7_EXPORT int hl7_in1_set_plan_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the plan_name (IN1.2.2) component as a string.
*/
HL7_EXPORT int hl7_in1_set_plan_name_str( HL7_Segment *segment, const char *value );
/**
* Get the company_id (IN1.3.1) component.
*/
HL7_EXPORT HL7_Element *hl7_in1_company_id( HL7_Segment *segment );
/**
* Set the company_id (IN1.3.1) component.
*/
HL7_EXPORT int hl7_in1_set_company_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the company_id (IN1.3.1) component as a string.
*/
HL7_EXPORT int hl7_in1_set_company_id_str( HL7_Segment *segment, const char *value );
/**
* Get the company_assigning_authority_id (IN1.3.4.1) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_in1_company_assigning_authority_id( HL7_Segment *segment );
/**
* Set the company_assigning_authority_id (IN1.3.4.1) subcomponent.
*/
HL7_EXPORT int hl7_in1_set_company_assigning_authority_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the company_assigning_authority_id (IN1.3.4.1) subcomponent as a string.
*/
HL7_EXPORT int hl7_in1_set_company_assigning_authority_id_str( HL7_Segment *segment, const char *value );
/**
* Get the company_id_type (IN1.3.4.5) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_in1_company_id_type( HL7_Segment *segment );
/**
* Set the company_id_type (IN1.3.4.5) subcomponent.
*/
HL7_EXPORT int hl7_in1_set_company_id_type( HL7_Segment *segment, HL7_Element *element );
/**
* Set the company_id_type (IN1.3.4.5) subcomponent as a string.
*/
HL7_EXPORT int hl7_in1_set_company_id_type_str( HL7_Segment *segment, const char *value );
/**
* Get the authorization_number (IN1.14.1) component.
*/
HL7_EXPORT HL7_Element *hl7_in1_authorization_number( HL7_Segment *segment );
/**
* Set the authorization_number (IN1.14.1) component.
*/
HL7_EXPORT int hl7_in1_set_authorization_number( HL7_Segment *segment, HL7_Element *element );
/**
* Set the authorization_number (IN1.14.1) component as a string.
*/
HL7_EXPORT int hl7_in1_set_authorization_number_str( HL7_Segment *segment, const char *value );
/**
* Get the auhtorization_date (IN1.14.2) component.
*/
HL7_EXPORT time_t hl7_in1_auhtorization_date( HL7_Segment *segment );
/**
* Set the auhtorization_date (IN1.14.2) component.
*/
HL7_EXPORT int hl7_in1_set_auhtorization_date( HL7_Segment *segment, HL7_Element *element );
/**
* Set the auhtorization_date (IN1.14.2) component as a time_t.
*/
HL7_EXPORT int hl7_in1_set_auhtorization_date_time( HL7_Segment *segment, const time_t value );

END_C_DECL()

#endif /* HL7_SEG_IN1_H */
