#ifndef HL7PARSER_SEG_MSA_H
#define HL7PARSER_SEG_MSA_H

/**
* \file seg_msa.h
*
* Message acknowledgment segment (MSA) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the ack_code (MSA.1) field.
*/
HL7_EXPORT HL7_Element *hl7_msa_ack_code( HL7_Segment *segment );
/**
* Set the ack_code (MSA.1) field.
*/
HL7_EXPORT int hl7_msa_set_ack_code( HL7_Segment *segment, HL7_Element *element );
/**
* Set the ack_code (MSA.1) field as a string.
*/
HL7_EXPORT int hl7_msa_set_ack_code_str( HL7_Segment *segment, const char *value );
/**
* Get the message_control_id (MSA.2) field.
*/
HL7_EXPORT HL7_Element *hl7_msa_message_control_id( HL7_Segment *segment );
/**
* Set the message_control_id (MSA.2) field.
*/
HL7_EXPORT int hl7_msa_set_message_control_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the message_control_id (MSA.2) field as a string.
*/
HL7_EXPORT int hl7_msa_set_message_control_id_str( HL7_Segment *segment, const char *value );
/**
* Get the error_code (MSA.6.1) component.
*/
HL7_EXPORT HL7_Element *hl7_msa_error_code( HL7_Segment *segment );
/**
* Set the error_code (MSA.6.1) component.
*/
HL7_EXPORT int hl7_msa_set_error_code( HL7_Segment *segment, HL7_Element *element );
/**
* Set the error_code (MSA.6.1) component as a string.
*/
HL7_EXPORT int hl7_msa_set_error_code_str( HL7_Segment *segment, const char *value );
/**
* Get the error_text (MSA.6.2) component.
*/
HL7_EXPORT HL7_Element *hl7_msa_error_text( HL7_Segment *segment );
/**
* Set the error_text (MSA.6.2) component.
*/
HL7_EXPORT int hl7_msa_set_error_text( HL7_Segment *segment, HL7_Element *element );
/**
* Set the error_text (MSA.6.2) component as a string.
*/
HL7_EXPORT int hl7_msa_set_error_text_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_MSA_H */
