#ifndef HL7PARSER_SEG_PRD_H
#define HL7PARSER_SEG_PRD_H

/**
* \file seg_prd.h
*
* Provider data segment (PRD) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the role_id (PRD.1.1.1) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_role_id( HL7_Segment *segment );
/**
* Set the role_id (PRD.1.1.1) component.
*/
HL7_EXPORT int hl7_prd_set_role_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the role_id (PRD.1.1.1) component as a string.
*/
HL7_EXPORT int hl7_prd_set_role_id_str( HL7_Segment *segment, const char *value );
/**
* Get the role_name (PRD.1.1.2) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_role_name( HL7_Segment *segment );
/**
* Set the role_name (PRD.1.1.2) component.
*/
HL7_EXPORT int hl7_prd_set_role_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the role_name (PRD.1.1.2) component as a string.
*/
HL7_EXPORT int hl7_prd_set_role_name_str( HL7_Segment *segment, const char *value );
/**
* Get the role_coding_system (PRD.1.1.3) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_role_coding_system( HL7_Segment *segment );
/**
* Set the role_coding_system (PRD.1.1.3) component.
*/
HL7_EXPORT int hl7_prd_set_role_coding_system( HL7_Segment *segment, HL7_Element *element );
/**
* Set the role_coding_system (PRD.1.1.3) component as a string.
*/
HL7_EXPORT int hl7_prd_set_role_coding_system_str( HL7_Segment *segment, const char *value );
/**
* Get the specialty_id (PRD.1.2.1) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_specialty_id( HL7_Segment *segment );
/**
* Set the specialty_id (PRD.1.2.1) component.
*/
HL7_EXPORT int hl7_prd_set_specialty_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the specialty_id (PRD.1.2.1) component as a string.
*/
HL7_EXPORT int hl7_prd_set_specialty_id_str( HL7_Segment *segment, const char *value );
/**
* Get the specialty_name (PRD.1.2.2) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_specialty_name( HL7_Segment *segment );
/**
* Set the specialty_name (PRD.1.2.2) component.
*/
HL7_EXPORT int hl7_prd_set_specialty_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the specialty_name (PRD.1.2.2) component as a string.
*/
HL7_EXPORT int hl7_prd_set_specialty_name_str( HL7_Segment *segment, const char *value );
/**
* Get the specialty_coding_system (PRD.1.2.3) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_specialty_coding_system( HL7_Segment *segment );
/**
* Set the specialty_coding_system (PRD.1.2.3) component.
*/
HL7_EXPORT int hl7_prd_set_specialty_coding_system( HL7_Segment *segment, HL7_Element *element );
/**
* Set the specialty_coding_system (PRD.1.2.3) component as a string.
*/
HL7_EXPORT int hl7_prd_set_specialty_coding_system_str( HL7_Segment *segment, const char *value );
/**
* Get the last_name (PRD.2.1) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_last_name( HL7_Segment *segment );
/**
* Set the last_name (PRD.2.1) component.
*/
HL7_EXPORT int hl7_prd_set_last_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the last_name (PRD.2.1) component as a string.
*/
HL7_EXPORT int hl7_prd_set_last_name_str( HL7_Segment *segment, const char *value );
/**
* Get the first_name (PRD.2.2) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_first_name( HL7_Segment *segment );
/**
* Set the first_name (PRD.2.2) component.
*/
HL7_EXPORT int hl7_prd_set_first_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the first_name (PRD.2.2) component as a string.
*/
HL7_EXPORT int hl7_prd_set_first_name_str( HL7_Segment *segment, const char *value );
/**
* Get the street (PRD.3.1) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_street( HL7_Segment *segment );
/**
* Set the street (PRD.3.1) component.
*/
HL7_EXPORT int hl7_prd_set_street( HL7_Segment *segment, HL7_Element *element );
/**
* Set the street (PRD.3.1) component as a string.
*/
HL7_EXPORT int hl7_prd_set_street_str( HL7_Segment *segment, const char *value );
/**
* Get the other_designation (PRD.3.2) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_other_designation( HL7_Segment *segment );
/**
* Set the other_designation (PRD.3.2) component.
*/
HL7_EXPORT int hl7_prd_set_other_designation( HL7_Segment *segment, HL7_Element *element );
/**
* Set the other_designation (PRD.3.2) component as a string.
*/
HL7_EXPORT int hl7_prd_set_other_designation_str( HL7_Segment *segment, const char *value );
/**
* Get the city (PRD.3.3) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_city( HL7_Segment *segment );
/**
* Set the city (PRD.3.3) component.
*/
HL7_EXPORT int hl7_prd_set_city( HL7_Segment *segment, HL7_Element *element );
/**
* Set the city (PRD.3.3) component as a string.
*/
HL7_EXPORT int hl7_prd_set_city_str( HL7_Segment *segment, const char *value );
/**
* Get the state (PRD.3.4) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_state( HL7_Segment *segment );
/**
* Set the state (PRD.3.4) component.
*/
HL7_EXPORT int hl7_prd_set_state( HL7_Segment *segment, HL7_Element *element );
/**
* Set the state (PRD.3.4) component as a string.
*/
HL7_EXPORT int hl7_prd_set_state_str( HL7_Segment *segment, const char *value );
/**
* Get the postal_code (PRD.3.5) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_postal_code( HL7_Segment *segment );
/**
* Set the postal_code (PRD.3.5) component.
*/
HL7_EXPORT int hl7_prd_set_postal_code( HL7_Segment *segment, HL7_Element *element );
/**
* Set the postal_code (PRD.3.5) component as a string.
*/
HL7_EXPORT int hl7_prd_set_postal_code_str( HL7_Segment *segment, const char *value );
/**
* Get the country_code (PRD.3.6) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_country_code( HL7_Segment *segment );
/**
* Set the country_code (PRD.3.6) component.
*/
HL7_EXPORT int hl7_prd_set_country_code( HL7_Segment *segment, HL7_Element *element );
/**
* Set the country_code (PRD.3.6) component as a string.
*/
HL7_EXPORT int hl7_prd_set_country_code_str( HL7_Segment *segment, const char *value );
/**
* Get the address_type (PRD.3.7) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_address_type( HL7_Segment *segment );
/**
* Set the address_type (PRD.3.7) component.
*/
HL7_EXPORT int hl7_prd_set_address_type( HL7_Segment *segment, HL7_Element *element );
/**
* Set the address_type (PRD.3.7) component as a string.
*/
HL7_EXPORT int hl7_prd_set_address_type_str( HL7_Segment *segment, const char *value );
/**
* Get the provider_id (PRD.7.1) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_provider_id( HL7_Segment *segment );
/**
* Set the provider_id (PRD.7.1) component.
*/
HL7_EXPORT int hl7_prd_set_provider_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the provider_id (PRD.7.1) component as a string.
*/
HL7_EXPORT int hl7_prd_set_provider_id_str( HL7_Segment *segment, const char *value );
/**
* Get the provider_id_type (PRD.7.2.1) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_prd_provider_id_type( HL7_Segment *segment );
/**
* Set the provider_id_type (PRD.7.2.1) subcomponent.
*/
HL7_EXPORT int hl7_prd_set_provider_id_type( HL7_Segment *segment, HL7_Element *element );
/**
* Set the provider_id_type (PRD.7.2.1) subcomponent as a string.
*/
HL7_EXPORT int hl7_prd_set_provider_id_type_str( HL7_Segment *segment, const char *value );
/**
* Get the provider_id_type_medical (PRD.7.2.2) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_prd_provider_id_type_medical( HL7_Segment *segment );
/**
* Set the provider_id_type_medical (PRD.7.2.2) subcomponent.
*/
HL7_EXPORT int hl7_prd_set_provider_id_type_medical( HL7_Segment *segment, HL7_Element *element );
/**
* Set the provider_id_type_medical (PRD.7.2.2) subcomponent as a string.
*/
HL7_EXPORT int hl7_prd_set_provider_id_type_medical_str( HL7_Segment *segment, const char *value );
/**
* Get the provider_id_type_province (PRD.7.2.3) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_prd_provider_id_type_province( HL7_Segment *segment );
/**
* Set the provider_id_type_province (PRD.7.2.3) subcomponent.
*/
HL7_EXPORT int hl7_prd_set_provider_id_type_province( HL7_Segment *segment, HL7_Element *element );
/**
* Set the provider_id_type_province (PRD.7.2.3) subcomponent as a string.
*/
HL7_EXPORT int hl7_prd_set_provider_id_type_province_str( HL7_Segment *segment, const char *value );
/**
* Get the provider_id_alternate_qualifier (PRD.7.3) component.
*/
HL7_EXPORT HL7_Element *hl7_prd_provider_id_alternate_qualifier( HL7_Segment *segment );
/**
* Set the provider_id_alternate_qualifier (PRD.7.3) component.
*/
HL7_EXPORT int hl7_prd_set_provider_id_alternate_qualifier( HL7_Segment *segment, HL7_Element *element );
/**
* Set the provider_id_alternate_qualifier (PRD.7.3) component as a string.
*/
HL7_EXPORT int hl7_prd_set_provider_id_alternate_qualifier_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_PRD_H */
