#ifndef HL7PARSER_SEG_PID_H
#define HL7PARSER_SEG_PID_H

/**
* \file seg_pid.h
*
* Patient information segment (PID) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the set_id (PID.1) field.
*/
HL7_EXPORT int hl7_pid_set_id( HL7_Segment *segment );
/**
* Set the set_id (PID.1) field.
*/
HL7_EXPORT int hl7_pid_set_set_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the set_id (PID.1) field as an integer.
*/
HL7_EXPORT int hl7_pid_set_set_id_int( HL7_Segment *segment, const int value );
/**
* Get the patient_id (PID.3.1.1) component.
*/
HL7_EXPORT HL7_Element *hl7_pid_patient_id( HL7_Segment *segment );
/**
* Set the patient_id (PID.3.1.1) component.
*/
HL7_EXPORT int hl7_pid_set_patient_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the patient_id (PID.3.1.1) component as a string.
*/
HL7_EXPORT int hl7_pid_set_patient_id_str( HL7_Segment *segment, const char *value );
/**
* Get the patient_document_id (PID.3.1.1) component.
*/
HL7_EXPORT HL7_Element *hl7_pid_patient_document_id( HL7_Segment *segment );
/**
* Set the patient_document_id (PID.3.1.1) component.
*/
HL7_EXPORT int hl7_pid_set_patient_document_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the patient_document_id (PID.3.1.1) component as a string.
*/
HL7_EXPORT int hl7_pid_set_patient_document_id_str( HL7_Segment *segment, const char *value );
/**
* Get the assigning_authority_id (PID.3.4.1) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_pid_assigning_authority_id( HL7_Segment *segment );
/**
* Set the assigning_authority_id (PID.3.4.1) subcomponent.
*/
HL7_EXPORT int hl7_pid_set_assigning_authority_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the assigning_authority_id (PID.3.4.1) subcomponent as a string.
*/
HL7_EXPORT int hl7_pid_set_assigning_authority_id_str( HL7_Segment *segment, const char *value );
/**
* Get the assigning_authority_universal_id (PID.3.4.2) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_pid_assigning_authority_universal_id( HL7_Segment *segment );
/**
* Set the assigning_authority_universal_id (PID.3.4.2) subcomponent.
*/
HL7_EXPORT int hl7_pid_set_assigning_authority_universal_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the assigning_authority_universal_id (PID.3.4.2) subcomponent as a string.
*/
HL7_EXPORT int hl7_pid_set_assigning_authority_universal_id_str( HL7_Segment *segment, const char *value );
/**
* Get the assigning_authority_universal_id_type (PID.3.4.3) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_pid_assigning_authority_universal_id_type( HL7_Segment *segment );
/**
* Set the assigning_authority_universal_id_type (PID.3.4.3) subcomponent.
*/
HL7_EXPORT int hl7_pid_set_assigning_authority_universal_id_type( HL7_Segment *segment, HL7_Element *element );
/**
* Set the assigning_authority_universal_id_type (PID.3.4.3) subcomponent as a string.
*/
HL7_EXPORT int hl7_pid_set_assigning_authority_universal_id_type_str( HL7_Segment *segment, const char *value );
/**
* Get the id_type (PID.3.5) component.
*/
HL7_EXPORT HL7_Element *hl7_pid_id_type( HL7_Segment *segment );
/**
* Set the id_type (PID.3.5) component.
*/
HL7_EXPORT int hl7_pid_set_id_type( HL7_Segment *segment, HL7_Element *element );
/**
* Set the id_type (PID.3.5) component as a string.
*/
HL7_EXPORT int hl7_pid_set_id_type_str( HL7_Segment *segment, const char *value );
/**
* Get the last_name (PID.5.1) component.
*/
HL7_EXPORT HL7_Element *hl7_pid_last_name( HL7_Segment *segment );
/**
* Set the last_name (PID.5.1) component.
*/
HL7_EXPORT int hl7_pid_set_last_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the last_name (PID.5.1) component as a string.
*/
HL7_EXPORT int hl7_pid_set_last_name_str( HL7_Segment *segment, const char *value );
/**
* Get the first_name (PID.5.2) component.
*/
HL7_EXPORT HL7_Element *hl7_pid_first_name( HL7_Segment *segment );
/**
* Set the first_name (PID.5.2) component.
*/
HL7_EXPORT int hl7_pid_set_first_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the first_name (PID.5.2) component as a string.
*/
HL7_EXPORT int hl7_pid_set_first_name_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_PID_H */
