#ifndef HL7PARSER_SEG_PR1_H
#define HL7PARSER_SEG_PR1_H

/**
* \file seg_pr1.h
*
* Procedure information segment (PR1) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the set_id (PR1.1) field.
*/
HL7_EXPORT int hl7_pr1_set_id( HL7_Segment *segment );
/**
* Set the set_id (PR1.1) field.
*/
HL7_EXPORT int hl7_pr1_set_set_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the set_id (PR1.1) field as an integer.
*/
HL7_EXPORT int hl7_pr1_set_set_id_int( HL7_Segment *segment, const int value );
/**
* Get the procedure_id (PR1.3.1) component.
*/
HL7_EXPORT HL7_Element *hl7_pr1_procedure_id( HL7_Segment *segment );
/**
* Set the procedure_id (PR1.3.1) component.
*/
HL7_EXPORT int hl7_pr1_set_procedure_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the procedure_id (PR1.3.1) component as a string.
*/
HL7_EXPORT int hl7_pr1_set_procedure_id_str( HL7_Segment *segment, const char *value );
/**
* Get the procedure_name (PR1.3.2) component.
*/
HL7_EXPORT HL7_Element *hl7_pr1_procedure_name( HL7_Segment *segment );
/**
* Set the procedure_name (PR1.3.2) component.
*/
HL7_EXPORT int hl7_pr1_set_procedure_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the procedure_name (PR1.3.2) component as a string.
*/
HL7_EXPORT int hl7_pr1_set_procedure_name_str( HL7_Segment *segment, const char *value );
/**
* Get the coding_system (PR1.3.3) component.
*/
HL7_EXPORT HL7_Element *hl7_pr1_coding_system( HL7_Segment *segment );
/**
* Set the coding_system (PR1.3.3) component.
*/
HL7_EXPORT int hl7_pr1_set_coding_system( HL7_Segment *segment, HL7_Element *element );
/**
* Set the coding_system (PR1.3.3) component as a string.
*/
HL7_EXPORT int hl7_pr1_set_coding_system_str( HL7_Segment *segment, const char *value );
/**
* Get the date (PR1.5) field.
*/
HL7_EXPORT time_t hl7_pr1_date( HL7_Segment *segment );
/**
* Set the date (PR1.5) field.
*/
HL7_EXPORT int hl7_pr1_set_date( HL7_Segment *segment, HL7_Element *element );
/**
* Set the date (PR1.5) field as a time_t.
*/
HL7_EXPORT int hl7_pr1_set_date_time( HL7_Segment *segment, const time_t value );

END_C_DECL()

#endif /* HL7_SEG_PR1_H */
