/**
* \file seg_pr1.c
*
* Procedure information segment (PR1) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_pr1.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_id( HL7_Segment *segment )
{
    return hl7_element_int( hl7_segment_field( segment, 0 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_set_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_set_id_int( HL7_Segment *segment, const int value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_int( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pr1_procedure_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_procedure_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_procedure_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pr1_procedure_name( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_procedure_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_procedure_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pr1_coding_system( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_coding_system( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_coding_system_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_pr1_date( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 4 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_date( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 4, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pr1_set_date_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, true, true, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 4, &element ) : rc );
}

END_C_DECL()
