/**
* \file seg_rf1.c
*
* Referral information segment (RF1) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_rf1.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rf1_referral_status_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_status_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_status_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 0, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rf1_referral_status_description( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 0, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_status_description( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 0, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_status_description_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 0, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rf1_referral_type_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_type_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_type_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rf1_referral_type_description( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_type_description( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_type_description_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rf1_originating_referral_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 5, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_originating_referral_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 5, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_originating_referral_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 5, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_rf1_effective_date( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 6 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_effective_date( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 6, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_effective_date_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, true, false, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 6, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_rf1_expiration_date( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 7 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_expiration_date( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 7, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_expiration_date_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, true, false, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 7, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_rf1_process_date( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 8 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_process_date( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 8, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_process_date_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, true, false, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 8, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rf1_referral_reason_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 9, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_reason_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 9, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rf1_set_referral_reason_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 9, 0, &element ) : rc );
}

END_C_DECL()
