/**
* \file seg_prd.c
*
* Provider data segment (PRD) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_prd.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_role_id( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 0, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_role_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 0, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_role_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 0, 0, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_role_name( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 0, 0, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_role_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 0, 0, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_role_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 0, 0, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_role_coding_system( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 0, 0, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_role_coding_system( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 0, 0, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_role_coding_system_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 0, 0, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_specialty_id( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 0, 1, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_specialty_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 0, 1, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_specialty_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 0, 1, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_specialty_name( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 0, 1, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_specialty_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 0, 1, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_specialty_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 0, 1, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_specialty_coding_system( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 0, 1, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_specialty_coding_system( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 0, 1, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_specialty_coding_system_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 0, 1, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_last_name( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 1, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_last_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 1, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_last_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 1, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_first_name( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 1, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_first_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 1, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_first_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 1, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_street( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_street( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_street_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_other_designation( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_other_designation( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_other_designation_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_city( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_city( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_city_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_state( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 3 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_state( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 3, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_state_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 3, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_postal_code( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 4 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_postal_code( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 4, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_postal_code_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 4, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_country_code( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 5 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_country_code( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 5, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_country_code_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 5, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_address_type( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 6 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_address_type( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 6, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_address_type_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 6, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_provider_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 6, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 6, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 6, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_provider_id_type( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 6, 1, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id_type( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 6, 1, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id_type_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 6, 1, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_provider_id_type_medical( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 6, 1, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id_type_medical( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 6, 1, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id_type_medical_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 6, 1, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_provider_id_type_province( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 6, 1, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id_type_province( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 6, 1, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id_type_province_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 6, 1, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_prd_provider_id_alternate_qualifier( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 6, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id_alternate_qualifier( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 6, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_prd_set_provider_id_alternate_qualifier_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 6, 2, &element ) : rc );
}

END_C_DECL()
