/**
* \file seg_qpd_q15.c
*
* Query parameter definition -- procedure totals query segment (QPD_Q15) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_qpd_q15.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_qpd_q15_query_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_query_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_query_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 0, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_qpd_q15_query_name( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 0, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_query_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 0, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_query_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 0, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_qpd_q15_query_tag( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_query_tag( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_query_tag_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_qpd_q15_provider_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_provider_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_provider_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_qpd_q15_provider_id_type( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_provider_id_type( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_provider_id_type_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_qpd_q15_start_date( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 3 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_start_date( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 3, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_start_date_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, true, false, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 3, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_qpd_q15_end_date( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 4 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_end_date( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 4, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_end_date_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, true, false, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 4, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_qpd_q15_procedure_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 5, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_procedure_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 5, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_procedure_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 5, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_qpd_q15_procedure_coding_system( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 5, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_procedure_coding_system( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 5, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_procedure_coding_system_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 5, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_qpd_q15_authorizer_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 6, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_authorizer_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 6, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_qpd_q15_set_authorizer_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 6, 0, &element ) : rc );
}

END_C_DECL()
