/**
* \file seg_aut.c
*
* Authorization information segment (AUT) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_aut.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_aut_plan_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_plan_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_plan_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 0, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_aut_plan_name( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 0, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_plan_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 0, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_plan_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 0, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_aut_company_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 1, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_company_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 1, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_company_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 1, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_aut_company_name( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 1, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_company_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 1, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_company_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 1, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_aut_company_id_coding_system( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 1, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_company_id_coding_system( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 1, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_company_id_coding_system_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 1, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_aut_start_date( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 3 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_start_date( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 3, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_start_date_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, false, false, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 3, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_aut_end_date( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 4 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_end_date( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 4, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_end_date_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, false, false, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 4, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_aut_authorization_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 5, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_authorization_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 5, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_authorization_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 5, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_requested_treatments( HL7_Segment *segment )
{
    return hl7_element_int( hl7_segment_field( segment, 7 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_requested_treatments( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 7, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_requested_treatments_int( HL7_Segment *segment, const int value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_int( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 7, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_authorized_treatments( HL7_Segment *segment )
{
    return hl7_element_int( hl7_segment_field( segment, 8 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_authorized_treatments( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 8, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_aut_set_authorized_treatments_int( HL7_Segment *segment, const int value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_int( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 8, &element ) : rc );
}

END_C_DECL()
