/**
* \file seg_pid.c
*
* Patient information segment (PID) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_pid.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_id( HL7_Segment *segment )
{
    return hl7_element_int( hl7_segment_field( segment, 0 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_set_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_set_id_int( HL7_Segment *segment, const int value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_int( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pid_patient_id( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 2, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_patient_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 2, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_patient_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 2, 0, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pid_patient_document_id( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 2, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_patient_document_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 2, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_patient_document_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 2, 0, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pid_assigning_authority_id( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 2, 3, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_assigning_authority_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 2, 3, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_assigning_authority_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 2, 3, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pid_assigning_authority_universal_id( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 2, 3, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_assigning_authority_universal_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 2, 3, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_assigning_authority_universal_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 2, 3, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pid_assigning_authority_universal_id_type( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 2, 3, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_assigning_authority_universal_id_type( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 2, 3, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_assigning_authority_universal_id_type_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 2, 3, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pid_id_type( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 4 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_id_type( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 4, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_id_type_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 4, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pid_last_name( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 4, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_last_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 4, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_last_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 4, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pid_first_name( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 4, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_first_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 4, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pid_set_first_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 4, 1, &element ) : rc );
}

END_C_DECL()
