/**
* \file seg_pv2.c
*
* Patient visit - additional information segment (PV2) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_pv2.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_pv2_transfer_reason_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 3, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pv2_set_transfer_reason_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 3, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_pv2_set_transfer_reason_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 3, 0, &element ) : rc );
}

END_C_DECL()
