/**
* \file seg_dsp.c
*
* Display data segment (DSP) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_dsp.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_id( HL7_Segment *segment )
{
    return hl7_element_int( hl7_segment_field( segment, 0 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_set_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_set_id_int( HL7_Segment *segment, const int value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_int( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_dsp_display_level( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_display_level( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_display_level_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_dsp_data_line( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_data_line( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_data_line_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_dsp_break_point( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 3 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_break_point( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 3, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_break_point_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 3, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_dsp_result_id( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 4 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_result_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 4, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_dsp_set_result_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 4, &element ) : rc );
}

END_C_DECL()
