/**
* \file seg_rcp.c
*
* Response control parameter segment (RCP) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2011 \b Erlar (http://erlar.com)
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the ./hl7segdef.py script on Mon Jun  6 12:54:47 2011
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_rcp.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rcp_query_priority( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_query_priority( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_query_priority_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_response_limit( HL7_Segment *segment )
{
    return hl7_element_int( hl7_segment_component( segment, 1, 0 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_response_limit( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 1, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_response_limit_int( HL7_Segment *segment, const int value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_int( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 1, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rcp_response_unit( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 1, 1, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_response_unit( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 1, 1, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_response_unit_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 1, 1, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rcp_response_modality_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_response_modality_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_response_modality_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_rcp_execution_date( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 3 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_execution_date( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 3, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_execution_date_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, true, false, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 3, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_rcp_sort_by( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 5 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_sort_by( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 5, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_rcp_set_sort_by_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 5, &element ) : rc );
}

END_C_DECL()
